spring.application.name=FoodOrdering


# =========================================================
# MySQL / JPA
# =========================================================

# Docker:
#   DB_URL=jdbc:mysql://mysql:3306/foodOrdering...
#
# Local:
#   falls back to localhost:3306/FoodOrdering

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/foodOrdering?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================================================
# Java Mail
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# =========================================================
# Kafka
# =========================================================

# Docker:
#   kafka:29092
#
# Local:
#   localhost:9092

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


# ---------------------------------------------------------
# Kafka Producer
# ---------------------------------------------------------

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# ---------------------------------------------------------
# Kafka Consumer
# ---------------------------------------------------------

spring.kafka.consumer.group-id=orders-groups

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


# ---------------------------------------------------------
# JSON Deserialization
# ---------------------------------------------------------

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.value.default.type=com.monolithic.FoodOrdering.orders.model.OrderEvent