services:

  # =======================================================
  # SPRING BOOT APPLICATION
  # =======================================================

  app:
    build: .

    container_name: foodOrdering-app

    ports:
      - "8080:8080"

    environment:

      # ---------------------------------------------------
      # MySQL
      # ---------------------------------------------------

      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

      DB_USERNAME: ${DB_USERNAME}

      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}


      # ---------------------------------------------------
      # Java Mail
      # ---------------------------------------------------

      MAIL_USERNAME: ${MAIL_USERNAME}

      MAIL_PASSWORD: ${MAIL_PASSWORD}


      # ---------------------------------------------------
      # Kafka
      # ---------------------------------------------------

      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - mysql
      - kafka

    networks:
      - foodOrdering-network


  # =======================================================
  # MYSQL
  # =======================================================

  mysql:
    image: mysql:8.0.44

    container_name: foodOrdering-mysql

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - foodOrdering-network


  # =======================================================
  # KAFKA
  # =======================================================

  kafka:
    image: apache/kafka:4.0.1

    container_name: foodOrdering-kafka

    ports:
      - "9092:9092"

    environment:

      # ---------------------------------------------------
      # KRaft
      # ---------------------------------------------------

      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller


      # ---------------------------------------------------
      # Listener configuration
      # ---------------------------------------------------

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092


      # ---------------------------------------------------
      # Controller
      # ---------------------------------------------------

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093


      # ---------------------------------------------------
      # Broker
      # ---------------------------------------------------

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


      # ---------------------------------------------------
      # Single broker settings
      # ---------------------------------------------------

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_NUM_PARTITIONS: 1

    networks:
      - foodOrdering-network


# =========================================================
# VOLUMES
# =========================================================

volumes:

  mysql-data:


# =========================================================
# NETWORK
# =========================================================

networks:

  foodOrdering-network:
    driver: bridge